# Generated by Django 5.2.8 on 2025-11-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=200)),
                ('tag', models.TextField()),
                ('due', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('isDone', models.BooleanField(default=False)),
            ],
        ),
    ]
